In [1]:
## one hot encoding using sklearn
from sklearn.preprocessing import OneHotEncoder
import numpy as np
data = np.array([['red'], ['green'], ['blue']])
encoder = OneHotEncoder()
print((encoder.fit_transform(data)))
encoded_data = encoder.fit_transform(data).toarray()
print(encoded_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [2]:
#Bag of Words using sklearn
from sklearn.feature_extraction.text import CountVectorizer
senteneces = ["I love programming", "I love love Python", "I enjoy machine learning"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(senteneces)
print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0 0 1 0 1 0]
 [0 0 2 0 0 1]
 [1 1 0 1 0 0]]
['enjoy' 'learning' 'love' 'machine' 'programming' 'python']
